name: Build DeClang with OLLVM

on: workflow_dispatch

jobs:
  build-declang:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: DeNA/DeClang
        ref: Android-v1.0.0
        submodules: true
        
    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build
        
    - name: Build Clang
      run: |
        cd llvm
        mkdir build && cd build
        
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_ENABLE_PROJECTS="clang" \
          -G "Ninja"
        
        ninja clang
        
    - name: Package
      run: |
        mkdir -p declang/bin
        cp llvm/build/bin/clang declang/bin/
        tar czf declang.tar.gz declang/
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: declang
        path: declang.tar.gz
